title: Wombat Wednesday
author: JRV
email: Jayarvee@duck.com
description: > # this means to ignore newlines until "twitter_username:"
  I made this site to help me put theory into practice. And I love wombats.

theme: minima
